services:
  app:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan octane:frankenphp --workers=3 --max-requests=500 --port=8000
    container_name: e-ticketing-app
    image: e-ticketing-app:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - vendor_data:/app/vendor
      - storage_data:/app/storage
      - cache_data:/app/bootstrap/cache
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - e-ticketing-network

  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: e-ticketing-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - e-ticketing-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    container_name: e-ticketing-redis
    networks:
      - e-ticketing-network

  worker:
    image: e-ticketing-app:latest
    env_file:
      - .env.docker
    container_name: e-ticketing-worker
    restart: unless-stopped
    entrypoint: php artisan queue:work --tries=3
    volumes:
      - .:/app
      - vendor_data:/app/vendor
      - storage_data:/app/storage
      - cache_data:/app/bootstrap/cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      app:
        condition: service_started
    networks:
      - e-ticketing-network

  scheduler:
    image: e-ticketing-app:latest
    env_file:
      - .env.docker
    container_name: e-ticketing-scheduler
    restart: unless-stopped
    entrypoint: php artisan schedule:work
    volumes:
      - .:/app
      - vendor_data:/app/vendor
      - storage_data:/app/storage
      - cache_data:/app/bootstrap/cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      app:
        condition: service_started
    networks:
      - e-ticketing-network

networks:
  e-ticketing-network:
    driver: bridge

volumes:
  storage_data:
  cache_data:
  postgres_data:
  vendor_data:
